Meteor.startup ->
  ServiceConfiguration.configurations.update { service: 'google' }, { $set:
    clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    client_email: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    secret: 'XXXXXXXXXXXXXXXXXXXXXXXX' }, upsert: true